# docker-compose.yml
version: '3.8'

services:

  # PostgreSql server
  postgres_db:
    image: postgres:14.1-alpine
    restart: on-failure:3
    volumes:
      - ./data/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=restx
      - POSTGRES_PASSWORD=restx123
      - POSTGRES_DB=restxdb
    networks:
      - network_db    
  
  # Redis server
  redis_db:
    image: redis:7.2.4-alpine
    hostname: redis
    restart: always
    command: redis-server --save 60 1 --loglevel warning #--requirepass ${REDIS_PASSWORD}
    volumes:
      - vol_redis:/var/lib/redis
      - vol_redis_config:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - network_db
    depends_on:
      - postgres_db
  
  # Redis GUI
  redis_gui:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=restx
      - HTTP_PASSWORD=restx123
    ports:
      - 8081:8081
    networks:
      - network_db
    depends_on:
      - redis_db

  # Flask Server [Yet to package]



volumes:
  vol_redis:
  vol_redis_config:

networks:
  network_db:
    driver: bridge
