# docker-compose.yml
version: '3.8'

services:

  # PostgreSql server
  postgres_db:
    image: postgres:14.1-alpine
    restart: on-failure:3
    volumes:
      - ./data/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - vol_pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=restx
      - POSTGRES_PASSWORD=restx123
      - POSTGRES_DB=restxdb
    networks:
      - network_db    
  
  # Redis server
  redis_db:
    image: redis/redis-stack:7.2.0-v10
    hostname: redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]    
    volumes:
      - vol_redis:/data
      - vol_redisinsight:/redisinsight
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - network_db
    depends_on:
      - postgres_db
  
  # Flask Server [Yet to package]



volumes:
  vol_pgdata:
  vol_redis:
  vol_redisinsight:

networks:
  network_db:
    driver: bridge
