version: '3.8'
services:
  # Redis server
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning 
    volumes: 
      - redis_data:/data
  # PostgreSql server
  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=default_database

  # Flask Server

volumes:
  postgres_data: 
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/postgres
      o: bind
  redis_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /data/redis
      o: bind
