services:

  # PostgreSql server
  postgres_db:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/db/postgres/:/var/lib/postgresql/data
      - ./data/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=restx
      - POSTGRES_PASSWORD=restx@123
      - POSTGRES_DB=restxdb
  
  # Redis server
  redis_db:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning 
    volumes: 
      - ./data/db/redis/:/data
    depends_on:
      - postgres_db

  # Flask Server [Yet to package]
