name: restx
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - git=2.43.0
  - tqdm=4.65.0
  - pytest=7.4.4
  - jupyterlab=4.0.11
  - pandas=2.2.0
  - pyarrow=11.0.0
  - pillow=10.2.0
  - matplotlib=3.8.0
  - opencv=4.9.0
  - flask-restx=1.3.0
  - flask-cors=4.0.0
  - earthengine-api
  - rasterio  
  - spectral
  - pip:
    - geetools

# conda create --name restx --clone flask
# conda env create -n restx --file environment.yml --force
# conda env update -n restx --file environment.yml --prune
# conda env remove -n restx